project:
  type: website
  output-dir: docs

website:
  title: "Buckley's & None code"
  google-analytics: "UA-136671602-2"

format:
  html:
    code-fold: show
    theme: flatly
    css: styles.css
    toc: true

editor: visual

