project:
  type: website
  output-dir: docs

website:
  title: "Buckley's & None code"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    code-fold: show
    theme: flatly
    css: styles.css
    toc: true

editor: visual

